In [14]:
import numpy as np 


In [15]:
x1 =np.array([2,3,1,5])
print(x1)
print(type(x1))

[2 3 1 5]
<class 'numpy.ndarray'>


In [16]:
x2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(x2)
print(type(x2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [17]:
# method to create matrix 
# 1d
# arange() - start,stop,step
#linspace() -start,stop,numofelements

#nd
#random.randint() -low,high,size

In [18]:
a=np.arange(10,51)
print(a)
print(a.shape) # gives the numbers of items in the array 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
(41,)


In [19]:
b = np.linspace(10,20,100)
print(b)

[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

In [20]:
c = np.random.randint(-10,20,(5,5))
print(c)

[[  3  13  -4   8  -5]
 [  6  10  10   9  -3]
 [ 13   2   4  15   1]
 [ 14  -3  -3  11   3]
 [-10   0  19  -5  11]]


In [21]:
a=np.array([
    [2,4,6],
    [1,3,5]
])
b=np.array([
    [1,2],
    [5,1],
    [3,2]
])
print(a,b,sep='\n')
print(a.dot(b)) # matrix multiplications ( dot product )

[[2 4 6]
 [1 3 5]]
[[1 2]
 [5 1]
 [3 2]]
[[40 20]
 [31 15]]


01/03/2024

properties 

In [22]:
x = np.random.randint(10,99,(4,5))
print(x)
print(x.reshape(5,4))
print(x.reshape(1,20))
print(x.reshape(20,1))
print(x.reshape(2,10))
print(x.reshape(10,2))

[[22 80 18 32 20]
 [78 44 44 94 25]
 [68 67 59 25 50]
 [16 98 13 10 18]]
[[22 80 18 32]
 [20 78 44 44]
 [94 25 68 67]
 [59 25 50 16]
 [98 13 10 18]]
[[22 80 18 32 20 78 44 44 94 25 68 67 59 25 50 16 98 13 10 18]]
[[22]
 [80]
 [18]
 [32]
 [20]
 [78]
 [44]
 [44]
 [94]
 [25]
 [68]
 [67]
 [59]
 [25]
 [50]
 [16]
 [98]
 [13]
 [10]
 [18]]
[[22 80 18 32 20 78 44 44 94 25]
 [68 67 59 25 50 16 98 13 10 18]]
[[22 80]
 [18 32]
 [20 78]
 [44 44]
 [94 25]
 [68 67]
 [59 25]
 [50 16]
 [98 13]
 [10 18]]


In [ ]:
print(x.flatten()) # n dimensional array to 1 dimensional array 


In [23]:
y = np.random.randint(10,99,(5,2))
print(y)

[[79 68]
 [90 20]
 [44 68]
 [94 90]
 [98 21]]


In [25]:
y.T

array([[79, 90, 44, 94, 98],
       [68, 20, 68, 90, 21]])

maths and stats 

In [27]:
a = np.array([
    [2,4],
    [1,3]
])
b = np.array([
    [1,2],
    [5,1]
])

# addition
print( a+b)
#subtractions
print(a-b)
#division
print(a/b)
#multiplications
print(a*b)
# dot product 
print(a@b) # matrix multiplication

[[3 6]
 [6 4]]
[[ 1  2]
 [-4  2]]
[[2.  2. ]
 [0.2 3. ]]
[[2 8]
 [5 3]]
[[22  8]
 [16  5]]


In [29]:
print(y.sum())  # summation of all elements 
print(y.sum(axis=0)) # summation of each column 
print(y.sum(axis=1)) # summation of each row 

# max and min 
print(y.max(),y.min())
#argmax and argim -> information about the index of the max and min 
print(y.argmax(), y.argmin())

672
[405 267]
[147 110 112 184 119]
98 20
8 3


slicing
  - 1d array 
  X[start:stop:step ]
  -2d array 
  x[ rowstart: rowstop :rowstep , colstart:colstop:colstep]    ,is used for go from row to colm 

In [30]:
x = np.random.randint(10,100,(10,10))
print(x)

[[53 76 27 80 80 75 62 73 69 81]
 [63 47 55 31 89 31 24 16 79 43]
 [44 58 45 38 66 45 38 86 87 89]
 [20 30 72 59 96 85 27 89 86 21]
 [79 24 79 57 36 88 45 36 25 88]
 [79 77 99 95 16 41 30 38 71 32]
 [35 86 31 80 48 76 58 70 22 55]
 [65 83 60 45 13 75 90 83 90 61]
 [46 84 11 22 57 14 95 19 51 51]
 [18 21 11 16 50 25 86 78 55 57]]


In [40]:
print(x[0,0])  # first element 
print(x[-1,-1]) # lat element 
print(x[-1]) # last row 
print(x[0]) # first row 
print(x[:,0]) #first column 
print(x[:,-1]) #first 5 rows of the second column 
print(x[-5:,3]) # first 5 rows of the fourth colum 
print(x[:,:3]) # first 3 column 
print(x[:,-3:]) # last 3 column 

53
57
[18 21 11 16 50 25 86 78 55 57]
[53 76 27 80 80 75 62 73 69 81]
[53 63 44 20 79 79 35 65 46 18]
[81 43 89 21 88 32 55 61 51 57]
[95 80 45 22 16]
[[53 76 27]
 [63 47 55]
 [44 58 45]
 [20 30 72]
 [79 24 79]
 [79 77 99]
 [35 86 31]
 [65 83 60]
 [46 84 11]
 [18 21 11]]
[[73 69 81]
 [16 79 43]
 [86 87 89]
 [89 86 21]
 [36 25 88]
 [38 71 32]
 [70 22 55]
 [83 90 61]
 [19 51 51]
 [78 55 57]]


In [43]:
# find index for any number 
print(np.where(x == 66))

(array([2], dtype=int64), array([4], dtype=int64))


In [ ]:
# count 
print(np.count_)